/**
 * Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Content', 'model/ContentSearchRefinement'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Content'), require('./ContentSearchRefinement'));
  } else {
    // Browser globals (root is window)
    if (!root.ShopApi) {
      root.ShopApi = {};
    }
    root.ShopApi.ContentSearchResult = factory(root.ShopApi.ApiClient, root.ShopApi.Content, root.ShopApi.ContentSearchRefinement);
  }
}(this, function(ApiClient, Content, ContentSearchRefinement) {
  'use strict';



  /**
   * The ContentSearchResult model module.
   * @module model/ContentSearchResult
   * @version 20.8
   */

  /**
   * Constructs a new <code>ContentSearchResult</code>.
   * Document representing a content search result.
   * @alias module:model/ContentSearchResult
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>ContentSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContentSearchResult} obj Optional instance to populate.
   * @return {module:model/ContentSearchResult} The populated <code>ContentSearchResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('count')) {
        obj['count'] = ApiClient.convertToType(data['count'], 'Number');
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [Object]);
      }
      if (data.hasOwnProperty('hits')) {
        obj['hits'] = ApiClient.convertToType(data['hits'], [Content]);
      }
      if (data.hasOwnProperty('next')) {
        obj['next'] = ApiClient.convertToType(data['next'], 'String');
      }
      if (data.hasOwnProperty('previous')) {
        obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
      }
      if (data.hasOwnProperty('query')) {
        obj['query'] = ApiClient.convertToType(data['query'], 'String');
      }
      if (data.hasOwnProperty('refinements')) {
        obj['refinements'] = ApiClient.convertToType(data['refinements'], [ContentSearchRefinement]);
      }
      if (data.hasOwnProperty('selected_refinements')) {
        obj['selected_refinements'] = ApiClient.convertToType(data['selected_refinements'], {'String': 'String'});
      }
      if (data.hasOwnProperty('start')) {
        obj['start'] = ApiClient.convertToType(data['start'], 'Number');
      }
      if (data.hasOwnProperty('total')) {
        obj['total'] = ApiClient.convertToType(data['total'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The number of returned documents.
   * @member {Number} count
   */
  exports.prototype['count'] = undefined;
  /**
   * @member {Array.<Object>} data
   */
  exports.prototype['data'] = undefined;
  /**
   * The sorted array of search hits. Can be empty.
   * @member {Array.<module:model/Content>} hits
   */
  exports.prototype['hits'] = undefined;
  /**
   * The URL of the next result page.
   * @member {String} next
   */
  exports.prototype['next'] = undefined;
  /**
   * The URL of the previous result page.
   * @member {String} previous
   */
  exports.prototype['previous'] = undefined;
  /**
   * The query String that was searched for.
   * @member {String} query
   */
  exports.prototype['query'] = undefined;
  /**
   * The sorted array of search refinements. Can be empty.
   * @member {Array.<module:model/ContentSearchRefinement>} refinements
   */
  exports.prototype['refinements'] = undefined;
  /**
   * Map of selected refinement attribute id/value(s) pairs. The sorting order is the same like in request URL.
   * @member {Object.<String, String>} selected_refinements
   */
  exports.prototype['selected_refinements'] = undefined;
  /**
   * The zero-based index of the first search hit to include in the result.
   * @member {Number} start
   */
  exports.prototype['start'] = undefined;
  /**
   * The total number of documents.
   * @member {Number} total
   */
  exports.prototype['total'] = undefined;



  return exports;
}));


