/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AlertDescriptor model module.
* @module models/AlertDescriptor
* @version 20.8
*/
export default class AlertDescriptor {
    /**
    * Constructs a new <code>AlertDescriptor</code>.
    * Document describing a single alert descriptor.
    * @alias module:models/AlertDescriptor
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AlertDescriptor</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/AlertDescriptor} obj Optional instance to populate.
    * @return {module:models/AlertDescriptor} The populated <code>AlertDescriptor</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlertDescriptor();
                        
            
            if (data.hasOwnProperty('application_context_path')) {
                obj['application_context_path'] = ApiClient.convertToType(data['application_context_path'], 'String');
            }
            if (data.hasOwnProperty('application_id')) {
                obj['application_id'] = ApiClient.convertToType(data['application_id'], 'String');
            }
            if (data.hasOwnProperty('context_object_type')) {
                obj['context_object_type'] = ApiClient.convertToType(data['context_object_type'], 'String');
            }
            if (data.hasOwnProperty('default_priority')) {
                obj['default_priority'] = ApiClient.convertToType(data['default_priority'], 'String');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('message_id')) {
                obj['message_id'] = ApiClient.convertToType(data['message_id'], 'String');
            }
        }
        return obj;
    }

    /**
    * The application context path.
    * @member {String} application_context_path
    */
    application_context_path = undefined;
    /**
    * The application ID.
    * @member {String} application_id
    */
    application_id = undefined;
    /**
    * The context object type.
    * @member {String} context_object_type
    */
    context_object_type = undefined;
    /**
    * The default priority.
    * @member {module:models/AlertDescriptor.DefaultPriorityEnum} default_priority
    */
    default_priority = undefined;
    /**
    * URL for this resource.
    * @member {String} link
    */
    link = undefined;
    /**
    * The message ID.
    * @member {String} message_id
    */
    message_id = undefined;



    /**
    * Allowed values for the <code>default_priority</code> property.
    * @enum {String}
    * @readonly
    */
    static DefaultPriorityEnum = {
        /**
         * value: "not_allowed"
         * @const
         */
        "not_allowed": "not_allowed",
        /**
         * value: "hidden"
         * @const
         */
        "hidden": "hidden",
        /**
         * value: "informational"
         * @const
         */
        "informational": "informational",
        /**
         * value: "warning"
         * @const
         */
        "warning": "warning",
        /**
         * value: "action_required"
         * @const
         */
        "action_required": "action_required"    };

}
