/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CartridgePathApiResponse model module.
* @module models/CartridgePathApiResponse
* @version 20.8
*/
export default class CartridgePathApiResponse {
    /**
    * Constructs a new <code>CartridgePathApiResponse</code>.
    * Response of cartridge path related operation
    * @alias module:models/CartridgePathApiResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CartridgePathApiResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CartridgePathApiResponse} obj Optional instance to populate.
    * @return {module:models/CartridgePathApiResponse} The populated <code>CartridgePathApiResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartridgePathApiResponse();
                        
            
            if (data.hasOwnProperty('cartridges')) {
                obj['cartridges'] = ApiClient.convertToType(data['cartridges'], 'String');
            }
            if (data.hasOwnProperty('site_id')) {
                obj['site_id'] = ApiClient.convertToType(data['site_id'], 'String');
            }
        }
        return obj;
    }

    /**
    * Updated cartridge path
    * @member {String} cartridges
    */
    cartridges = undefined;
    /**
    * Site id
    * @member {String} site_id
    */
    site_id = undefined;




}
