/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CartridgePathCreateRequest model module.
* @module models/CartridgePathCreateRequest
* @version 20.8
*/
export default class CartridgePathCreateRequest {
    /**
    * Constructs a new <code>CartridgePathCreateRequest</code>.
    * Request Body for put operation
    * @alias module:models/CartridgePathCreateRequest
    * @class
    * @param cartridges {String} New cartridge path
    */

    constructor(cartridges) {
        
        
        this['cartridges'] = cartridges;
        
    }

    /**
    * Constructs a <code>CartridgePathCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CartridgePathCreateRequest} obj Optional instance to populate.
    * @return {module:models/CartridgePathCreateRequest} The populated <code>CartridgePathCreateRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartridgePathCreateRequest();
                        
            
            if (data.hasOwnProperty('cartridges')) {
                obj['cartridges'] = ApiClient.convertToType(data['cartridges'], 'String');
            }
        }
        return obj;
    }

    /**
    * New cartridge path
    * @member {String} cartridges
    */
    cartridges = undefined;




}
