/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CodeVersion model module.
* @module models/CodeVersion
* @version 20.8
*/
export default class CodeVersion {
    /**
    * Constructs a new <code>CodeVersion</code>.
    * Document representing a code version
    * @alias module:models/CodeVersion
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CodeVersion</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CodeVersion} obj Optional instance to populate.
    * @return {module:models/CodeVersion} The populated <code>CodeVersion</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CodeVersion();
                        
            
            if (data.hasOwnProperty('activation_time')) {
                obj['activation_time'] = ApiClient.convertToType(data['activation_time'], 'Date');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('cartridges')) {
                obj['cartridges'] = ApiClient.convertToType(data['cartridges'], ['String']);
            }
            if (data.hasOwnProperty('compatibility_mode')) {
                obj['compatibility_mode'] = ApiClient.convertToType(data['compatibility_mode'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('last_modification_time')) {
                obj['last_modification_time'] = ApiClient.convertToType(data['last_modification_time'], 'Date');
            }
            if (data.hasOwnProperty('rollback')) {
                obj['rollback'] = ApiClient.convertToType(data['rollback'], 'Boolean');
            }
            if (data.hasOwnProperty('total_size')) {
                obj['total_size'] = ApiClient.convertToType(data['total_size'], 'Number');
            }
            if (data.hasOwnProperty('web_dav_url')) {
                obj['web_dav_url'] = ApiClient.convertToType(data['web_dav_url'], 'String');
            }
        }
        return obj;
    }

    /**
    * The code version activation time.
    * @member {Date} activation_time
    */
    activation_time = undefined;
    /**
    * Use this method to determine, if this code version is currently active.
    * @member {Boolean} active
    */
    active = undefined;
    /**
    * A list containing the names of all cartridges participating in this code version.
    * @member {Array.<String>} cartridges
    */
    cartridges = undefined;
    /**
    * The code version compatibility mode.
    * @member {String} compatibility_mode
    */
    compatibility_mode = undefined;
    /**
    * The code version id.
    * @member {String} id
    */
    id = undefined;
    /**
    * The last time, when the code version was changed.
    * @member {Date} last_modification_time
    */
    last_modification_time = undefined;
    /**
    * Use this method to determine, if this code version is the current rollback version.
    * @member {Boolean} rollback
    */
    rollback = undefined;
    /**
    * Returns the total size of the file system content of this code version in bytes.
    * @member {Number} total_size
    */
    total_size = undefined;
    /**
    * Returns the HTTPS based WebDAV URL that can be used to access the code version resources.
    * @member {String} web_dav_url
    */
    web_dav_url = undefined;




}
