/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MediaFile from './MediaFile';

/**
* The ContentFolder model module.
* @module models/ContentFolder
* @version 20.8
*/
export default class ContentFolder {
    /**
    * Constructs a new <code>ContentFolder</code>.
    * Document representing a content folder.
    * @alias module:models/ContentFolder
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ContentFolder</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/ContentFolder} obj Optional instance to populate.
    * @return {module:models/ContentFolder} The populated <code>ContentFolder</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContentFolder();
                        
            
            if (data.hasOwnProperty('c_customCSSFile')) {
                obj['c_customCSSFile'] = MediaFile.constructFromObject(data['c_customCSSFile']);
            }
            if (data.hasOwnProperty('creation_date')) {
                obj['creation_date'] = ApiClient.convertToType(data['creation_date'], 'Date');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], {'String': 'String'});
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('last_modified')) {
                obj['last_modified'] = ApiClient.convertToType(data['last_modified'], 'Date');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], {'String': 'String'});
            }
            if (data.hasOwnProperty('online')) {
                obj['online'] = ApiClient.convertToType(data['online'], 'Boolean');
            }
            if (data.hasOwnProperty('page_description')) {
                obj['page_description'] = ApiClient.convertToType(data['page_description'], {'String': 'String'});
            }
            if (data.hasOwnProperty('page_keywords')) {
                obj['page_keywords'] = ApiClient.convertToType(data['page_keywords'], {'String': 'String'});
            }
            if (data.hasOwnProperty('page_title')) {
                obj['page_title'] = ApiClient.convertToType(data['page_title'], {'String': 'String'});
            }
            if (data.hasOwnProperty('page_url')) {
                obj['page_url'] = ApiClient.convertToType(data['page_url'], {'String': 'String'});
            }
            if (data.hasOwnProperty('parent_folder_id')) {
                obj['parent_folder_id'] = ApiClient.convertToType(data['parent_folder_id'], 'String');
            }
            if (data.hasOwnProperty('parent_link')) {
                obj['parent_link'] = ApiClient.convertToType(data['parent_link'], 'String');
            }
            if (data.hasOwnProperty('sub_folders_link')) {
                obj['sub_folders_link'] = ApiClient.convertToType(data['sub_folders_link'], 'String');
            }
            if (data.hasOwnProperty('template')) {
                obj['template'] = ApiClient.convertToType(data['template'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:models/MediaFile} c_customCSSFile
    */
    c_customCSSFile = undefined;
    /**
    * Returns the value of attribute 'creationDate'.
    * @member {Date} creation_date
    */
    creation_date = undefined;
    /**
    * The localized content folder description.
    * @member {Object.<String, String>} description
    */
    description = undefined;
    /**
    * The id of the content folder.
    * @member {String} id
    */
    id = undefined;
    /**
    * Returns the value of attribute 'lastModified'.
    * @member {Date} last_modified
    */
    last_modified = undefined;
    /**
    * The link to the content folder resource.
    * @member {String} link
    */
    link = undefined;
    /**
    * The localized content folder name.
    * @member {Object.<String, String>} name
    */
    name = undefined;
    /**
    * A flag indicating whether the folder in online (default is false).
    * @member {Boolean} online
    */
    online = undefined;
    /**
    * The localized content folder page description.
    * @member {Object.<String, String>} page_description
    */
    page_description = undefined;
    /**
    * The localized content folder page keywords.
    * @member {Object.<String, String>} page_keywords
    */
    page_keywords = undefined;
    /**
    * The localized content folder page title.
    * @member {Object.<String, String>} page_title
    */
    page_title = undefined;
    /**
    * The localized content folder page URL.
    * @member {Object.<String, String>} page_url
    */
    page_url = undefined;
    /**
    * The id of the parent content folder.
    * @member {String} parent_folder_id
    */
    parent_folder_id = undefined;
    /**
    * The URL to the parent content folder.
    * @member {String} parent_link
    */
    parent_link = undefined;
    /**
    * The URL to list the content sub-folders.
    * @member {String} sub_folders_link
    */
    sub_folders_link = undefined;
    /**
    * The rendering template.
    * @member {String} template
    */
    template = undefined;




}
