/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Rule from './Rule';

/**
* The CustomerGroup model module.
* @module models/CustomerGroup
* @version 20.8
*/
export default class CustomerGroup {
    /**
    * Constructs a new <code>CustomerGroup</code>.
    * Document representing a customer group
    * @alias module:models/CustomerGroup
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CustomerGroup</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CustomerGroup} obj Optional instance to populate.
    * @return {module:models/CustomerGroup} The populated <code>CustomerGroup</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerGroup();
                        
            
            if (data.hasOwnProperty('creation_date')) {
                obj['creation_date'] = ApiClient.convertToType(data['creation_date'], 'Date');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('in_deletion')) {
                obj['in_deletion'] = ApiClient.convertToType(data['in_deletion'], 'Boolean');
            }
            if (data.hasOwnProperty('last_modified')) {
                obj['last_modified'] = ApiClient.convertToType(data['last_modified'], 'Date');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('member_count')) {
                obj['member_count'] = ApiClient.convertToType(data['member_count'], 'Number');
            }
            if (data.hasOwnProperty('rule')) {
                obj['rule'] = Rule.constructFromObject(data['rule']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * Returns the value of attribute 'creationDate'.
    * @member {Date} creation_date
    */
    creation_date = undefined;
    /**
    * The description for the customer group.  This property is read-only for system groups.
    * @member {String} description
    */
    description = undefined;
    /**
    * The user specific identifier for the customer group, which must be unique across the organization.  Property  is read-only.
    * @member {String} id
    */
    id = undefined;
    /**
    * The deletion status of this customer group.
    * @member {Boolean} in_deletion
    */
    in_deletion = undefined;
    /**
    * Returns the value of attribute 'lastModified'.
    * @member {Date} last_modified
    */
    last_modified = undefined;
    /**
    * URL that is used to get this instance.  This property is computed and cannot be modified.
    * @member {String} link
    */
    link = undefined;
    /**
    * The number of members in this customer group.
    * @member {Number} member_count
    */
    member_count = undefined;
    /**
    * @member {module:models/Rule} rule
    */
    rule = undefined;
    /**
    * The type of the customer group.  This property is read-only.
    * @member {module:models/CustomerGroup.TypeEnum} type
    */
    type = undefined;



    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
        /**
         * value: "system"
         * @const
         */
        "system": "system",
        /**
         * value: "dynamic"
         * @const
         */
        "dynamic": "dynamic",
        /**
         * value: "static"
         * @const
         */
        "static": "static"    };

}
