/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CustomerList model module.
* @module models/CustomerList
* @version 20.8
*/
export default class CustomerList {
    /**
    * Constructs a new <code>CustomerList</code>.
    * Document representing a customer list.
    * @alias module:models/CustomerList
    * @class
    * @param id {String} The id of the customer list.
    */

    constructor(id) {
        
        
        this['id'] = id;
        
    }

    /**
    * Constructs a <code>CustomerList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/CustomerList} obj Optional instance to populate.
    * @return {module:models/CustomerList} The populated <code>CustomerList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerList();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
    * The id of the customer list.
    * @member {String} id
    */
    id = undefined;




}
