/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The OrderExternalStatusUpdateRequest model module.
* @module models/OrderExternalStatusUpdateRequest
* @version 20.8
*/
export default class OrderExternalStatusUpdateRequest {
    /**
    * Constructs a new <code>OrderExternalStatusUpdateRequest</code>.
    * Request body to update the order external status.
    * @alias module:models/OrderExternalStatusUpdateRequest
    * @class
    * @param status {String} The new external status for an order.
    */

    constructor(status) {
        
        
        this['status'] = status;
        
    }

    /**
    * Constructs a <code>OrderExternalStatusUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/OrderExternalStatusUpdateRequest} obj Optional instance to populate.
    * @return {module:models/OrderExternalStatusUpdateRequest} The populated <code>OrderExternalStatusUpdateRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderExternalStatusUpdateRequest();
                        
            
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
    * The new external status for an order.
    * @member {String} status
    */
    status = undefined;




}
