/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The PaymentTransactionUpdateRequest model module.
* @module models/PaymentTransactionUpdateRequest
* @version 20.8
*/
export default class PaymentTransactionUpdateRequest {
    /**
    * Constructs a new <code>PaymentTransactionUpdateRequest</code>.
    * Request body to update an order payment transaction.
    * @alias module:models/PaymentTransactionUpdateRequest
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>PaymentTransactionUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/PaymentTransactionUpdateRequest} obj Optional instance to populate.
    * @return {module:models/PaymentTransactionUpdateRequest} The populated <code>PaymentTransactionUpdateRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentTransactionUpdateRequest();
                        
            
        }
        return obj;
    }





}
