/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Promotion from './Promotion';

/**
* The Promotions model module.
* @module models/Promotions
* @version 20.8
*/
export default class Promotions {
    /**
    * Constructs a new <code>Promotions</code>.
    * A set of promotions
    * @alias module:models/Promotions
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Promotions</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:models/Promotions} obj Optional instance to populate.
    * @return {module:models/Promotions} The populated <code>Promotions</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Promotions();
                        
            
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Promotion]);
            }
            if (data.hasOwnProperty('expand')) {
                obj['expand'] = ApiClient.convertToType(data['expand'], ['String']);
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
            if (data.hasOwnProperty('previous')) {
                obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
            }
            if (data.hasOwnProperty('select')) {
                obj['select'] = ApiClient.convertToType(data['select'], 'String');
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} count
    */
    count = undefined;
    /**
    * The set of promotions
    * @member {Array.<module:models/Promotion>} data
    */
    data = undefined;
    /**
    * @member {Array.<String>} expand
    */
    expand = undefined;
    /**
    * @member {String} next
    */
    next = undefined;
    /**
    * @member {String} previous
    */
    previous = undefined;
    /**
    * @member {String} select
    */
    select = undefined;
    /**
    * @member {Number} start
    */
    start = undefined;
    /**
    * @member {Number} total
    */
    total = undefined;




}
