/**
 * Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.0.0-beta
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AlertItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AlertItem'));
  } else {
    // Browser globals (root is window)
    if (!root.DataApi) {
      root.DataApi = {};
    }
    root.DataApi.AlertItems = factory(root.DataApi.ApiClient, root.DataApi.AlertItem);
  }
}(this, function(ApiClient, AlertItem) {
  'use strict';



  /**
   * The AlertItems model module.
   * @module model/AlertItems
   * @version 20.8
   */

  /**
   * Constructs a new <code>AlertItems</code>.
   * Document containing a collection of alerts.
   * @alias module:model/AlertItems
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>AlertItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AlertItems} obj Optional instance to populate.
   * @return {module:model/AlertItems} The populated <code>AlertItems</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [AlertItem]);
      }
    }
    return obj;
  }

  /**
   * Collection of alerts
   * @member {Array.<module:model/AlertItem>} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


