/**
 * Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DataApi) {
      root.DataApi = {};
    }
    root.DataApi.CartridgePathCreateRequest = factory(root.DataApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The CartridgePathCreateRequest model module.
   * @module model/CartridgePathCreateRequest
   * @version 20.4
   */

  /**
   * Constructs a new <code>CartridgePathCreateRequest</code>.
   * Request Body for put operation
   * @alias module:model/CartridgePathCreateRequest
   * @class
   * @param cartridges {String} New cartridge path
   */
  var exports = function(cartridges) {
    var _this = this;

    _this['cartridges'] = cartridges;
  };

  /**
   * Constructs a <code>CartridgePathCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CartridgePathCreateRequest} obj Optional instance to populate.
   * @return {module:model/CartridgePathCreateRequest} The populated <code>CartridgePathCreateRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('cartridges')) {
        obj['cartridges'] = ApiClient.convertToType(data['cartridges'], 'String');
      }
    }
    return obj;
  }

  /**
   * New cartridge path
   * @member {String} cartridges
   */
  exports.prototype['cartridges'] = undefined;



  return exports;
}));


