/**
 * Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModulePermissions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModulePermissions'));
  } else {
    // Browser globals (root is window)
    if (!root.DataApi) {
      root.DataApi = {};
    }
    root.DataApi.Cscpermissions = factory(root.DataApi.ApiClient, root.DataApi.ModulePermissions);
  }
}(this, function(ApiClient, ModulePermissions) {
  'use strict';



  /**
   * The Cscpermissions model module.
   * @module model/Cscpermissions
   * @version 20.8
   */

  /**
   * Constructs a new <code>Cscpermissions</code>.
   * @alias module:model/Cscpermissions
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Cscpermissions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Cscpermissions} obj Optional instance to populate.
   * @return {module:model/Cscpermissions} The populated <code>Cscpermissions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('module')) {
        obj['module'] = ModulePermissions.constructFromObject(data['module']);
      }
      if (data.hasOwnProperty('module_link')) {
        obj['module_link'] = ApiClient.convertToType(data['module_link'], 'String');
      }
      if (data.hasOwnProperty('types')) {
        obj['types'] = ApiClient.convertToType(data['types'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ModulePermissions} module
   */
  exports.prototype['module'] = undefined;
  /**
   * @member {String} module_link
   */
  exports.prototype['module_link'] = undefined;
  /**
   * @member {Array.<String>} types
   */
  exports.prototype['types'] = undefined;



  return exports;
}));


