/**
 * Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.0.0-beta
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DataApi) {
      root.DataApi = {};
    }
    root.DataApi.ObjectTypeDefinition = factory(root.DataApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ObjectTypeDefinition model module.
   * @module model/ObjectTypeDefinition
   * @version 20.8
   */

  /**
   * Constructs a new <code>ObjectTypeDefinition</code>.
   * Document representing a object type definition
   * @alias module:model/ObjectTypeDefinition
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>ObjectTypeDefinition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ObjectTypeDefinition} obj Optional instance to populate.
   * @return {module:model/ObjectTypeDefinition} The populated <code>ObjectTypeDefinition</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('attribute_definition_count')) {
        obj['attribute_definition_count'] = ApiClient.convertToType(data['attribute_definition_count'], 'Number');
      }
      if (data.hasOwnProperty('attribute_group_count')) {
        obj['attribute_group_count'] = ApiClient.convertToType(data['attribute_group_count'], 'Number');
      }
      if (data.hasOwnProperty('content_object')) {
        obj['content_object'] = ApiClient.convertToType(data['content_object'], 'Boolean');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], {'String': 'String'});
      }
      if (data.hasOwnProperty('display_name')) {
        obj['display_name'] = ApiClient.convertToType(data['display_name'], {'String': 'String'});
      }
      if (data.hasOwnProperty('link')) {
        obj['link'] = ApiClient.convertToType(data['link'], 'String');
      }
      if (data.hasOwnProperty('object_type')) {
        obj['object_type'] = ApiClient.convertToType(data['object_type'], 'String');
      }
      if (data.hasOwnProperty('queryable')) {
        obj['queryable'] = ApiClient.convertToType(data['queryable'], 'Boolean');
      }
      if (data.hasOwnProperty('read_only')) {
        obj['read_only'] = ApiClient.convertToType(data['read_only'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Returns the number of attribute definitions contained by the type.  This is a computed attribute and cannot be changed.
   * @member {Number} attribute_definition_count
   */
  exports.prototype['attribute_definition_count'] = undefined;
  /**
   * Returns the number of attribute groups contained by the type.  This is a computed attribute and cannot be changed.
   * @member {Number} attribute_group_count
   */
  exports.prototype['attribute_group_count'] = undefined;
  /**
   * True if the object type definition is marked as a content object
   * @member {Boolean} content_object
   */
  exports.prototype['content_object'] = undefined;
  /**
   * The user entered description for the type (localizable)
   * @member {Object.<String, String>} description
   */
  exports.prototype['description'] = undefined;
  /**
   * The user entered display name (localizable)
   * @member {Object.<String, String>} display_name
   */
  exports.prototype['display_name'] = undefined;
  /**
   * URL that is used to get this instance.  This is a computed attribute and cannot be changed.
   * @member {String} link
   */
  exports.prototype['link'] = undefined;
  /**
   * The object type identifier
   * @member {String} object_type
   */
  exports.prototype['object_type'] = undefined;
  /**
   * True if the system object type is queryable, false otherwise.  Default is true.
   * @member {Boolean} queryable
   */
  exports.prototype['queryable'] = undefined;
  /**
   * True if the system object is read-only, false otherwise.  This is a computed attribute and cannot be changed.
   * @member {Boolean} read_only
   */
  exports.prototype['read_only'] = undefined;



  return exports;
}));


