/**
 * Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DataApi) {
      root.DataApi = {};
    }
    root.DataApi.OrderStatusUpdateRequest = factory(root.DataApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The OrderStatusUpdateRequest model module.
   * @module model/OrderStatusUpdateRequest
   * @version 20.8
   */

  /**
   * Constructs a new <code>OrderStatusUpdateRequest</code>.
   * Request body to update the order status.
   * @alias module:model/OrderStatusUpdateRequest
   * @class
   * @param status {module:model/OrderStatusUpdateRequest.StatusEnum} The new status for an order.
   */
  var exports = function(status) {
    var _this = this;

    _this['status'] = status;
  };

  /**
   * Constructs a <code>OrderStatusUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderStatusUpdateRequest} obj Optional instance to populate.
   * @return {module:model/OrderStatusUpdateRequest} The populated <code>OrderStatusUpdateRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * The new status for an order.
   * @member {module:model/OrderStatusUpdateRequest.StatusEnum} status
   */
  exports.prototype['status'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "created"
     * @const
     */
    "created": "created",
    /**
     * value: "new"
     * @const
     */
    "new": "new",
    /**
     * value: "open"
     * @const
     */
    "open": "open",
    /**
     * value: "completed"
     * @const
     */
    "completed": "completed",
    /**
     * value: "cancelled"
     * @const
     */
    "cancelled": "cancelled",
    /**
     * value: "failed"
     * @const
     */
    "failed": "failed"  };


  return exports;
}));


