/**
 * Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SitePreferences'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SitePreferences'));
  } else {
    // Browser globals (root is window)
    if (!root.DataApi) {
      root.DataApi = {};
    }
    root.DataApi.OrganizationPreferences = factory(root.DataApi.ApiClient, root.DataApi.SitePreferences);
  }
}(this, function(ApiClient, SitePreferences) {
  'use strict';



  /**
   * The OrganizationPreferences model module.
   * @module model/OrganizationPreferences
   * @version 20.8
   */

  /**
   * Constructs a new <code>OrganizationPreferences</code>.
   * Represents a set of preferences attached at the organization level.
   * @alias module:model/OrganizationPreferences
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>OrganizationPreferences</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrganizationPreferences} obj Optional instance to populate.
   * @return {module:model/OrganizationPreferences} The populated <code>OrganizationPreferences</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('link')) {
        obj['link'] = ApiClient.convertToType(data['link'], 'String');
      }
      if (data.hasOwnProperty('site_preferences')) {
        obj['site_preferences'] = ApiClient.convertToType(data['site_preferences'], [SitePreferences]);
      }
    }
    return obj;
  }

  /**
   * A URL that returns the full details for a custom preference
   * @member {String} link
   */
  exports.prototype['link'] = undefined;
  /**
   * The list of site preferences, returned with expand=sites
   * @member {Array.<module:model/SitePreferences>} site_preferences
   */
  exports.prototype['site_preferences'] = undefined;



  return exports;
}));


