/**
 * Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DataApi) {
      root.DataApi = {};
    }
    root.DataApi.RedemptionLimitPerPeriod = factory(root.DataApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The RedemptionLimitPerPeriod model module.
   * @module model/RedemptionLimitPerPeriod
   * @version 20.8
   */

  /**
   * Constructs a new <code>RedemptionLimitPerPeriod</code>.
   * Document representing a coupon redemption limit.
   * @alias module:model/RedemptionLimitPerPeriod
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>RedemptionLimitPerPeriod</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RedemptionLimitPerPeriod} obj Optional instance to populate.
   * @return {module:model/RedemptionLimitPerPeriod} The populated <code>RedemptionLimitPerPeriod</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('limit')) {
        obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
      }
      if (data.hasOwnProperty('redemption_time_frame')) {
        obj['redemption_time_frame'] = ApiClient.convertToType(data['redemption_time_frame'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The limit on the number of times a coupon can be redeemed for a specified redemption time period.
   * @member {Number} limit
   */
  exports.prototype['limit'] = undefined;
  /**
   * The redemption time period.
   * @member {Number} redemption_time_frame
   */
  exports.prototype['redemption_time_frame'] = undefined;



  return exports;
}));


