/**
 * Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.0.0-beta
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CustomerListLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CustomerListLink'));
  } else {
    // Browser globals (root is window)
    if (!root.DataApi) {
      root.DataApi = {};
    }
    root.DataApi.Site = factory(root.DataApi.ApiClient, root.DataApi.CustomerListLink);
  }
}(this, function(ApiClient, CustomerListLink) {
  'use strict';



  /**
   * The Site model module.
   * @module model/Site
   * @version 20.8
   */

  /**
   * Constructs a new <code>Site</code>.
   * Document representing a site.
   * @alias module:model/Site
   * @class
   * @param id {String} The id of this site.
   */
  var exports = function(id) {
    var _this = this;

    _this['id'] = id;
  };

  /**
   * Constructs a <code>Site</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Site} obj Optional instance to populate.
   * @return {module:model/Site} The populated <code>Site</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('cartridges')) {
        obj['cartridges'] = ApiClient.convertToType(data['cartridges'], 'String');
      }
      if (data.hasOwnProperty('customer_list_link')) {
        obj['customer_list_link'] = CustomerListLink.constructFromObject(data['customer_list_link']);
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], {'String': 'String'});
      }
      if (data.hasOwnProperty('display_name')) {
        obj['display_name'] = ApiClient.convertToType(data['display_name'], {'String': 'String'});
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('in_deletion')) {
        obj['in_deletion'] = ApiClient.convertToType(data['in_deletion'], 'Boolean');
      }
      if (data.hasOwnProperty('link')) {
        obj['link'] = ApiClient.convertToType(data['link'], 'String');
      }
      if (data.hasOwnProperty('storefront_status')) {
        obj['storefront_status'] = ApiClient.convertToType(data['storefront_status'], 'String');
      }
    }
    return obj;
  }

  /**
   * The cartridge Path of the site
   * @member {String} cartridges
   */
  exports.prototype['cartridges'] = undefined;
  /**
   * @member {module:model/CustomerListLink} customer_list_link
   */
  exports.prototype['customer_list_link'] = undefined;
  /**
   * The description of this site.
   * @member {Object.<String, String>} description
   */
  exports.prototype['description'] = undefined;
  /**
   * The display name entered by the user.
   * @member {Object.<String, String>} display_name
   */
  exports.prototype['display_name'] = undefined;
  /**
   * The id of this site.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The deletion status of this site, true if in deletion
   * @member {Boolean} in_deletion
   */
  exports.prototype['in_deletion'] = undefined;
  /**
   * A link directly to the site
   * @member {String} link
   */
  exports.prototype['link'] = undefined;
  /**
   * 
   * @member {module:model/Site.StorefrontStatusEnum} storefront_status
   */
  exports.prototype['storefront_status'] = undefined;


  /**
   * Allowed values for the <code>storefront_status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StorefrontStatusEnum = {
    /**
     * value: "online"
     * @const
     */
    "online": "online",
    /**
     * value: "maintenance"
     * @const
     */
    "maintenance": "maintenance",
    /**
     * value: "to_be_deleted"
     * @const
     */
    "to_be_deleted": "to_be_deleted",
    /**
     * value: "protected"
     * @const
     */
    "protected": "protected"  };


  return exports;
}));


