/**
 * Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DataApi) {
      root.DataApi = {};
    }
    root.DataApi.SourceCodeRedirectInfo = factory(root.DataApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The SourceCodeRedirectInfo model module.
   * @module model/SourceCodeRedirectInfo
   * @version 20.4
   */

  /**
   * Constructs a new <code>SourceCodeRedirectInfo</code>.
   * Document representing a source code redirect info
   * @alias module:model/SourceCodeRedirectInfo
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>SourceCodeRedirectInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SourceCodeRedirectInfo} obj Optional instance to populate.
   * @return {module:model/SourceCodeRedirectInfo} The populated <code>SourceCodeRedirectInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('location')) {
        obj['location'] = ApiClient.convertToType(data['location'], 'String');
      }
      if (data.hasOwnProperty('location_type')) {
        obj['location_type'] = ApiClient.convertToType(data['location_type'], 'String');
      }
    }
    return obj;
  }

  /**
   * The location of redirect, based on the type, this can be a product location, category location, home page, content page, or just a URL
   * @member {String} location
   */
  exports.prototype['location'] = undefined;
  /**
   * The type of redirect location, e.g. product (for a product page), category (a category page), home (for home page), page (for content), url (for a URL location)
   * @member {module:model/SourceCodeRedirectInfo.LocationTypeEnum} location_type
   */
  exports.prototype['location_type'] = undefined;


  /**
   * Allowed values for the <code>location_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.LocationTypeEnum = {
    /**
     * value: "default"
     * @const
     */
    "default": "default",
    /**
     * value: "home"
     * @const
     */
    "home": "home",
    /**
     * value: "product"
     * @const
     */
    "product": "product",
    /**
     * value: "category"
     * @const
     */
    "category": "category",
    /**
     * value: "page"
     * @const
     */
    "page": "page",
    /**
     * value: "url"
     * @const
     */
    "url": "url"  };


  return exports;
}));


