/**
 * Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.0.0-beta
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DataApi);
  }
}(this, function(expect, DataApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    // create a new instance
    //instance = new DataApi.Coupon();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Coupon', function() {
    it('should create an instance of Coupon', function() {
      // uncomment below and update the code to test Coupon
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be.a(DataApi.Coupon);
    });

    it('should have the property couponId (base name: "coupon_id")', function() {
      // uncomment below and update the code to test the property couponId
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property creationDate (base name: "creation_date")', function() {
      // uncomment below and update the code to test the property creationDate
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property exportedCodeCount (base name: "exported_code_count")', function() {
      // uncomment below and update the code to test the property exportedCodeCount
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property lastModified (base name: "last_modified")', function() {
      // uncomment below and update the code to test the property lastModified
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property link (base name: "link")', function() {
      // uncomment below and update the code to test the property link
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property redemptionCount (base name: "redemption_count")', function() {
      // uncomment below and update the code to test the property redemptionCount
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property redemptionLimits (base name: "redemption_limits")', function() {
      // uncomment below and update the code to test the property redemptionLimits
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property singleCode (base name: "single_code")', function() {
      // uncomment below and update the code to test the property singleCode
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property systemCodesConfig (base name: "system_codes_config")', function() {
      // uncomment below and update the code to test the property systemCodesConfig
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property totalCodesCount (base name: "total_codes_count")', function() {
      // uncomment below and update the code to test the property totalCodesCount
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new DataApi.Coupon();
      //expect(instance).to.be();
    });

  });

}));
