/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DataApi);
  }
}(this, function(expect, DataApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DataApi.CouponCode();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CouponCode', function() {
    it('should create an instance of CouponCode', function() {
      // uncomment below and update the code to test CouponCode
      //var instane = new DataApi.CouponCode();
      //expect(instance).to.be.a(DataApi.CouponCode);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instane = new DataApi.CouponCode();
      //expect(instance).to.be();
    });

    it('should have the property issued (base name: "issued")', function() {
      // uncomment below and update the code to test the property issued
      //var instane = new DataApi.CouponCode();
      //expect(instance).to.be();
    });

    it('should have the property redemptionCount (base name: "redemption_count")', function() {
      // uncomment below and update the code to test the property redemptionCount
      //var instane = new DataApi.CouponCode();
      //expect(instance).to.be();
    });

  });

}));
