/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DataApi);
  }
}(this, function(expect, DataApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DataApi.ProductInventoryRecord();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductInventoryRecord', function() {
    it('should create an instance of ProductInventoryRecord', function() {
      // uncomment below and update the code to test ProductInventoryRecord
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be.a(DataApi.ProductInventoryRecord);
    });

    it('should have the property allocation (base name: "allocation")', function() {
      // uncomment below and update the code to test the property allocation
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property ats (base name: "ats")', function() {
      // uncomment below and update the code to test the property ats
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property creationDate (base name: "creation_date")', function() {
      // uncomment below and update the code to test the property creationDate
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property inStockDate (base name: "in_stock_date")', function() {
      // uncomment below and update the code to test the property inStockDate
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property inventoryListId (base name: "inventory_list_id")', function() {
      // uncomment below and update the code to test the property inventoryListId
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property inventoryTurnover (base name: "inventory_turnover")', function() {
      // uncomment below and update the code to test the property inventoryTurnover
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property lastModified (base name: "last_modified")', function() {
      // uncomment below and update the code to test the property lastModified
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property link (base name: "link")', function() {
      // uncomment below and update the code to test the property link
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property perpetualFlag (base name: "perpetual_flag")', function() {
      // uncomment below and update the code to test the property perpetualFlag
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property preOrderBackOrderAllocation (base name: "pre_order_back_order_allocation")', function() {
      // uncomment below and update the code to test the property preOrderBackOrderAllocation
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property preOrderBackOrderHandling (base name: "pre_order_back_order_handling")', function() {
      // uncomment below and update the code to test the property preOrderBackOrderHandling
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property productId (base name: "product_id")', function() {
      // uncomment below and update the code to test the property productId
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property productName (base name: "product_name")', function() {
      // uncomment below and update the code to test the property productName
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property quantityOnOrder (base name: "quantity_on_order")', function() {
      // uncomment below and update the code to test the property quantityOnOrder
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

    it('should have the property stockLevel (base name: "stock_level")', function() {
      // uncomment below and update the code to test the property stockLevel
      //var instane = new DataApi.ProductInventoryRecord();
      //expect(instance).to.be();
    });

  });

}));
