/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DataApi);
  }
}(this, function(expect, DataApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DataApi.SourceCodeGroup();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SourceCodeGroup', function() {
    it('should create an instance of SourceCodeGroup', function() {
      // uncomment below and update the code to test SourceCodeGroup
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be.a(DataApi.SourceCodeGroup);
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be();
    });

    it('should have the property activeRedirect (base name: "active_redirect")', function() {
      // uncomment below and update the code to test the property activeRedirect
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be();
    });

    it('should have the property cookieDuration (base name: "cookie_duration")', function() {
      // uncomment below and update the code to test the property cookieDuration
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be();
    });

    it('should have the property creationDate (base name: "creation_date")', function() {
      // uncomment below and update the code to test the property creationDate
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be();
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be();
    });

    it('should have the property endTime (base name: "end_time")', function() {
      // uncomment below and update the code to test the property endTime
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be();
    });

    it('should have the property inactiveRedirect (base name: "inactive_redirect")', function() {
      // uncomment below and update the code to test the property inactiveRedirect
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be();
    });

    it('should have the property lastModified (base name: "last_modified")', function() {
      // uncomment below and update the code to test the property lastModified
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be();
    });

    it('should have the property link (base name: "link")', function() {
      // uncomment below and update the code to test the property link
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be();
    });

    it('should have the property specifications (base name: "specifications")', function() {
      // uncomment below and update the code to test the property specifications
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be();
    });

    it('should have the property startTime (base name: "start_time")', function() {
      // uncomment below and update the code to test the property startTime
      //var instane = new DataApi.SourceCodeGroup();
      //expect(instance).to.be();
    });

  });

}));
