/**
 * Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DataApi);
  }
}(this, function(expect, DataApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DataApi.VariationAttribute();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VariationAttribute', function() {
    it('should create an instance of VariationAttribute', function() {
      // uncomment below and update the code to test VariationAttribute
      //var instane = new DataApi.VariationAttribute();
      //expect(instance).to.be.a(DataApi.VariationAttribute);
    });

    it('should have the property attributeDefinitionId (base name: "attribute_definition_id")', function() {
      // uncomment below and update the code to test the property attributeDefinitionId
      //var instane = new DataApi.VariationAttribute();
      //expect(instance).to.be();
    });

    it('should have the property attributeDefinitionName (base name: "attribute_definition_name")', function() {
      // uncomment below and update the code to test the property attributeDefinitionName
      //var instane = new DataApi.VariationAttribute();
      //expect(instance).to.be();
    });

    it('should have the property defaultValue (base name: "default_value")', function() {
      // uncomment below and update the code to test the property defaultValue
      //var instane = new DataApi.VariationAttribute();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new DataApi.VariationAttribute();
      //expect(instance).to.be();
    });

    it('should have the property link (base name: "link")', function() {
      // uncomment below and update the code to test the property link
      //var instane = new DataApi.VariationAttribute();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new DataApi.VariationAttribute();
      //expect(instance).to.be();
    });

    it('should have the property shared (base name: "shared")', function() {
      // uncomment below and update the code to test the property shared
      //var instane = new DataApi.VariationAttribute();
      //expect(instance).to.be();
    });

    it('should have the property slicing (base name: "slicing")', function() {
      // uncomment below and update the code to test the property slicing
      //var instane = new DataApi.VariationAttribute();
      //expect(instance).to.be();
    });

    it('should have the property values (base name: "values")', function() {
      // uncomment below and update the code to test the property values
      //var instane = new DataApi.VariationAttribute();
      //expect(instance).to.be();
    });

    it('should have the property variationAttributeType (base name: "variation_attribute_type")', function() {
      // uncomment below and update the code to test the property variationAttributeType
      //var instane = new DataApi.VariationAttribute();
      //expect(instance).to.be();
    });

  });

}));
