/**
 * Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.0.0-beta
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ShopApi);
  }
}(this, function(expect, ShopApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ShopApi.ProductSearchApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductSearchApi', function() {
    describe('getProductSearch', function() {
      it('should call getProductSearch successfully', function(done) {
        //uncomment below and update the code to test getProductSearch
        //instance.getProductSearch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductSearchAvailability', function() {
      it('should call getProductSearchAvailability successfully', function(done) {
        //uncomment below and update the code to test getProductSearchAvailability
        //instance.getProductSearchAvailability(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductSearchImages', function() {
      it('should call getProductSearchImages successfully', function(done) {
        //uncomment below and update the code to test getProductSearchImages
        //instance.getProductSearchImages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductSearchPrices', function() {
      it('should call getProductSearchPrices successfully', function(done) {
        //uncomment below and update the code to test getProductSearchPrices
        //instance.getProductSearchPrices(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductSearchRepresentedProducts', function() {
      it('should call getProductSearchRepresentedProducts successfully', function(done) {
        //uncomment below and update the code to test getProductSearchRepresentedProducts
        //instance.getProductSearchRepresentedProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductSearchVariations', function() {
      it('should call getProductSearchVariations successfully', function(done) {
        //uncomment below and update the code to test getProductSearchVariations
        //instance.getProductSearchVariations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
