/**
 * Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.0.0-beta
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DataApi);
  }
}(this, function(expect, DataApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DataApi.CodeVersionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CodeVersionsApi', function() {
    describe('deleteCodeVersionsByID', function() {
      it('should call deleteCodeVersionsByID successfully', function(done) {
        //uncomment below and update the code to test deleteCodeVersionsByID
        //instance.deleteCodeVersionsByID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCodeVersions', function() {
      it('should call getCodeVersions successfully', function(done) {
        //uncomment below and update the code to test getCodeVersions
        //instance.getCodeVersions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCodeVersionsByID', function() {
      it('should call getCodeVersionsByID successfully', function(done) {
        //uncomment below and update the code to test getCodeVersionsByID
        //instance.getCodeVersionsByID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchCodeVersionsByID', function() {
      it('should call patchCodeVersionsByID successfully', function(done) {
        //uncomment below and update the code to test patchCodeVersionsByID
        //instance.patchCodeVersionsByID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCodeVersionsByID', function() {
      it('should call putCodeVersionsByID successfully', function(done) {
        //uncomment below and update the code to test putCodeVersionsByID
        //instance.putCodeVersionsByID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
