/**
 * Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.0.0-beta
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DataApi);
  }
}(this, function(expect, DataApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DataApi.OcapiConfigsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OcapiConfigsApi', function() {
    describe('deleteOcapiConfigsByID', function() {
      it('should call deleteOcapiConfigsByID successfully', function(done) {
        //uncomment below and update the code to test deleteOcapiConfigsByID
        //instance.deleteOcapiConfigsByID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOcapiConfigsByID', function() {
      it('should call getOcapiConfigsByID successfully', function(done) {
        //uncomment below and update the code to test getOcapiConfigsByID
        //instance.getOcapiConfigsByID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postOcapiConfigsByID', function() {
      it('should call postOcapiConfigsByID successfully', function(done) {
        //uncomment below and update the code to test postOcapiConfigsByID
        //instance.postOcapiConfigsByID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOcapiConfigsByID', function() {
      it('should call putOcapiConfigsByID successfully', function(done) {
        //uncomment below and update the code to test putOcapiConfigsByID
        //instance.putOcapiConfigsByID(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
