/**
 * Shop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.0.0-beta
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ShopApi);
  }
}(this, function(expect, ShopApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    // create a new instance
    //instance = new ShopApi.PriceAdjustment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PriceAdjustment', function() {
    it('should create an instance of PriceAdjustment', function() {
      // uncomment below and update the code to test PriceAdjustment
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be.a(ShopApi.PriceAdjustment);
    });

    it('should have the property appliedDiscount (base name: "applied_discount")', function() {
      // uncomment below and update the code to test the property appliedDiscount
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be();
    });

    it('should have the property couponCode (base name: "coupon_code")', function() {
      // uncomment below and update the code to test the property couponCode
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "created_by")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be();
    });

    it('should have the property creationDate (base name: "creation_date")', function() {
      // uncomment below and update the code to test the property creationDate
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be();
    });

    it('should have the property custom (base name: "custom")', function() {
      // uncomment below and update the code to test the property custom
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be();
    });

    it('should have the property itemText (base name: "item_text")', function() {
      // uncomment below and update the code to test the property itemText
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be();
    });

    it('should have the property lastModified (base name: "last_modified")', function() {
      // uncomment below and update the code to test the property lastModified
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be();
    });

    it('should have the property manual (base name: "manual")', function() {
      // uncomment below and update the code to test the property manual
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be();
    });

    it('should have the property priceAdjustmentId (base name: "price_adjustment_id")', function() {
      // uncomment below and update the code to test the property priceAdjustmentId
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be();
    });

    it('should have the property promotionId (base name: "promotion_id")', function() {
      // uncomment below and update the code to test the property promotionId
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be();
    });

    it('should have the property promotionLink (base name: "promotion_link")', function() {
      // uncomment below and update the code to test the property promotionLink
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be();
    });

    it('should have the property reasonCode (base name: "reason_code")', function() {
      // uncomment below and update the code to test the property reasonCode
      //var instance = new ShopApi.PriceAdjustment();
      //expect(instance).to.be();
    });

  });

}));
